export const locales = ['es', 'pt', 'zh'] as const;
export type Locale = (typeof locales)[number];

export const languageNames: Record<Locale, string> = { es: 'ES', pt: 'PT', zh: '中文' };

export const dictionaries = {
  es: {
    localeName: 'Español', htmlLang: 'es-AR',
    seo: { title: 'Vértice Sino | Proveedores y tecnología industrial de China', description: 'Consultoría para empresas de Argentina y América Latina: búsqueda y evaluación de proveedores chinos, comparación de soluciones y vinculación industrial.' },
    nav: ['Inicio', 'Servicios', 'Cómo trabajamos', 'Nosotros', 'FAQ', 'Contacto'], cta: 'Solicitar asesoría', menuLabel: 'Abrir menú',
    hero: { eyebrow: 'ARGENTINA · BRASIL · AMÉRICA LATINA', title: 'Conectamos su empresa con el potencial industrial de China.', lead: 'Encontramos, evaluamos y acercamos proveedores y tecnologías para que su empresa tome decisiones de abastecimiento con mejor información.', process: 'Conocer nuestro proceso', note: ['Información que cruza fronteras.', 'Decisiones que hacen avanzar.'], latam: 'LATAM', china: 'CHINA', core: ['Una visión clara', 'para decidir mejor'], stats: [['Mercado','Investigación enfocada'],['Criterio','Análisis comparable']] },
    trust: ['Menos incertidumbre','Mejores comparaciones','Comunicación más fluida'],
    services: { eyebrow: 'Servicios', title: 'Convertimos sus necesidades en opciones concretas dentro del mercado chino.', intro: 'Transformamos una búsqueda amplia y compleja en opciones concretas, comparables y relevantes para su empresa.', items: [['Búsqueda y selección de proveedores','Buscamos fabricantes según el producto, equipo, tecnología, presupuesto, cantidad y objetivos del proyecto.'],['Revisión y contraste de información','Organizamos la información aportada por los proveedores y contrastamos datos empresariales, productos, cotizaciones, MOQ (cantidad mínima de pedido), plazos de entrega y condiciones comerciales relevantes.'],['Comparación de cotizaciones y soluciones','Comparamos las alternativas con dimensiones claras: precio, MOQ, plazo de entrega, condiciones de pago y requisitos técnicos.'],['Comunicación directa y coordinación','Gestionamos la comunicación comercial necesaria en chino como parte del proceso de búsqueda, evaluación y coordinación.'],['Manufactura y tecnología moderna','Exploramos equipos, fabricación inteligente y nuevas tecnologías productivas según la necesidad real del cliente.'],['Automatización y robótica','Identificamos soluciones de automatización comercial e industrial, robótica de servicio y equipos inteligentes.'],['Construcción modular','Investigamos sistemas prefabricados y soluciones modulares para empresas y proyectos específicos.'],['Consultoría y sourcing de proveedores','Estudiamos productos, equipos o tecnologías no listados en la web y buscamos alternativas de fabricación adecuadas.']] },
    capabilities: { eyebrow: 'Industrias y soluciones', title: 'Áreas en las que podemos buscar proveedores y soluciones.', intro: 'No ofrecemos un catálogo fijo: partimos de la necesidad real de cada empresa para buscar proveedores, equipos, tecnologías y soluciones en el mercado chino.', items: [['Automatización y robótica','Equipos, integración y eficiencia operativa'],['Manufactura avanzada','Procesos, componentes y capacidad productiva'],['Construcción modular','Sistemas prefabricados y soluciones de proyecto'],['Equipamiento comercial e industrial','Equipos para operaciones comerciales, de servicio y productivas'],['Soluciones tecnológicas','Tecnología aplicada a necesidades empresariales concretas'],['Sourcing personalizado','Investigación adaptada a requisitos específicos']] },
    process: { eyebrow: 'Cómo trabajamos', title: 'Un proceso ordenado, desde la necesidad hasta la coordinación.', intro: 'Cada proyecto comienza con sus criterios, no con un catálogo.', items: [['Entender la necesidad','Definimos producto, equipo o tecnología, cantidad, presupuesto, requisitos, uso y objetivo.'],['Buscar proveedores','Localizamos fabricantes y proveedores potenciales dentro del mercado chino.'],['Evaluar y organizar','Reunimos información empresarial y técnica, precio, MOQ, plazo de entrega, condiciones de pago y requisitos técnicos.'],['Comparar alternativas','Presentamos una comparación estructurada de las dimensiones centrales para facilitar la evaluación del cliente.'],['Coordinar','Apoyamos la comunicación y el enlace posterior. La decisión comercial final siempre corresponde al cliente.']] },
    about: { eyebrow: 'Nosotros', graphic: ['VÉRTICE','Perspectiva local','Acceso global','SINO'], title: 'Más cerca de China. Más cerca de una buena decisión.', paragraphs: ['Vértice Sino nace para ayudar a empresas de Argentina y América Latina a entender y aprovechar la capacidad industrial china con una mirada profesional, independiente y orientada al negocio.','Actuamos como consultores y facilitadores: aportamos investigación, comparación y comunicación para que cada cliente conserve el control de sus decisiones.'], link: 'Conversemos sobre su proyecto' },
    scope: { eyebrow: 'Nuestro alcance', title: 'Claridad también significa saber cuál es nuestro rol.', intro: 'Acompañamos la búsqueda, evaluación y coordinación. La contratación y el pago se realizan directamente entre el cliente y el proveedor seleccionado.', items: [['Análisis y búsqueda de proveedores','Analizamos necesidades, buscamos proveedores y organizamos y revisamos la información recibida.'],['Comparación y coordinación','Comparamos cotizaciones y soluciones, y apoyamos la comunicación comercial con proveedores en China.'],['Contratación directa','El cliente contrata y paga directamente al proveedor final.'],['Pagos','No recibimos pagos de mercadería ni pagamos proveedores por el cliente.'],['Importación','No actuamos como importador ni gestionamos la importación final en el país del cliente.'],['Alcance profesional','No somos vendedores de productos ni ofrecemos traducción como servicio independiente. La comunicación en chino forma parte de la consultoría y coordinación del proyecto.']] },
    faq: { eyebrow: 'Preguntas frecuentes', title: 'Respuestas claras antes de comenzar.', items: [['¿Cómo funciona el servicio?','Comenzamos entendiendo la necesidad. Luego buscamos proveedores, organizamos y contrastamos información, comparamos alternativas y coordinamos el contacto según la decisión del cliente.'],['¿Cómo se cobra la asesoría?','Los honorarios dependen de la complejidad, el alcance de búsqueda, el trabajo de investigación y los servicios requeridos. La propuesta se informa antes de comenzar.'],['¿Vértice Sino importa los productos?','No. Brindamos consultoría de compras, búsqueda y coordinación. El cliente gestiona la importación según las normas de su país o mediante especialistas en comercio exterior y logística.'],['¿A quién paga el cliente?','El cliente paga directamente al proveedor chino finalmente seleccionado. Vértice Sino no recibe pagos destinados a mercadería.'],['¿Cómo seleccionan proveedores?','Organizamos y comparamos el perfil del proveedor, la adecuación del producto y cinco dimensiones centrales: precio, MOQ, plazo de entrega, condiciones de pago y requisitos técnicos. Este análisis reduce incertidumbre, pero no elimina todos los riesgos comerciales.'],['¿Cuánto demora un proyecto?','Depende de la complejidad del producto, los requisitos técnicos, la velocidad de respuesta de los proveedores, la cantidad de alternativas y el alcance acordado.'],['¿Pueden buscar algo que no aparece en la web?','Sí. Las áreas mostradas son orientativas. Podemos investigar otros productos, equipos y tecnologías de fabricación china según una necesidad empresarial concreta.']] },
    contact: { eyebrow: 'Contacto', title: 'Cuéntenos qué está buscando.', intro: 'Comparta los datos principales de su proyecto. Revisaremos la consulta para evaluar cómo podemos acompañarlo.', whatsapp: ['Escríbanos por','WhatsApp'], fields: { name: ['Nombre y apellido','Su nombre'], company: ['Empresa','Nombre de la empresa'], country: ['País','Argentina'], email: ['Email','nombre@empresa.com'], whatsapp: ['WhatsApp / teléfono (opcional)','Código de país y número'], product: ['Producto o tecnología buscada','¿Qué necesita encontrar?'], message: ['Descripción del proyecto','Uso, requisitos técnicos y objetivos'], budget: ['Presupuesto aproximado (opcional)','Rango estimado'], quantity: ['Cantidad estimada (opcional)','Unidades o volumen'], deadline: ['Plazo esperado (opcional)','Fecha o período estimado'] }, submit: 'Enviar consulta', privacy: 'Al enviar, se abrirá su aplicación de correo con la consulta preparada. Revise el mensaje y confirme el envío desde allí.' },
    footer: { tagline: 'Conexiones industriales con criterio.', copyright: '© 2026 Vértice Sino' },
  },
  pt: {
    localeName: 'Português', htmlLang: 'pt-BR',
    seo: { title: 'Vértice Sino | Fornecedores e tecnologia industrial da China', description: 'Consultoria para empresas do Brasil e da América Latina: busca e avaliação de fornecedores chineses, comparação de soluções e conexão industrial.' },
    nav: ['Início', 'Serviços', 'Como trabalhamos', 'Sobre nós', 'FAQ', 'Contato'], cta: 'Solicitar consultoria', menuLabel: 'Abrir menu',
    hero: { eyebrow: 'BRASIL · ARGENTINA · AMÉRICA LATINA', title: 'Conectamos sua empresa ao potencial industrial da China.', lead: 'Identificamos, avaliamos e aproximamos fornecedores e tecnologias para que sua empresa tome decisões de compras com informações mais consistentes.', process: 'Conheça nosso processo', note: ['Informação que atravessa fronteiras.', 'Decisões que impulsionam negócios.'], latam: 'LATAM', china: 'CHINA', core: ['Uma visão clara', 'para decidir melhor'], stats: [['Mercado','Pesquisa direcionada'],['Critério','Análise comparável']] },
    trust: ['Menos incerteza','Comparações melhores','Comunicação mais fluida'],
    services: { eyebrow: 'Serviços', title: 'Transformamos suas necessidades em opções concretas no mercado chinês.', intro: 'Transformamos uma busca ampla e complexa em opções concretas, comparáveis e relevantes para sua empresa.', items: [['Busca e seleção de fornecedores','Buscamos fabricantes conforme o produto, equipamento, tecnologia, orçamento, quantidade e objetivos do projeto.'],['Revisão e cruzamento de informações','Organizamos as informações fornecidas e cruzamos dados empresariais, produtos, propostas, MOQ (quantidade mínima de pedido), prazos e condições comerciais relevantes.'],['Comparação de propostas e soluções','Comparamos as alternativas por dimensões claras: preço, MOQ, prazo de entrega, condições de pagamento e requisitos técnicos.'],['Comunicação direta e coordenação','Conduzimos a comunicação comercial necessária em chinês como parte da busca, avaliação e coordenação.'],['Manufatura e tecnologia moderna','Exploramos equipamentos, fabricação inteligente e novas tecnologias produtivas conforme a necessidade do cliente.'],['Automação e robótica','Identificamos automação comercial e industrial, robôs de serviço e equipamentos inteligentes.'],['Construção modular','Pesquisamos sistemas pré-fabricados e soluções modulares para empresas e projetos.'],['Consultoria e sourcing de fornecedores','Estudamos produtos, equipamentos ou tecnologias não listados e buscamos alternativas de fabricação adequadas.']] },
    capabilities: { eyebrow: 'Setores e soluções', title: 'Áreas em que podemos buscar fornecedores e soluções.', intro: 'Não trabalhamos com um catálogo fixo: partimos da necessidade real de cada empresa para buscar fornecedores, equipamentos, tecnologias e soluções no mercado chinês.', items: [['Automação e robótica','Equipamentos, integração e eficiência operacional'],['Manufatura avançada','Processos, componentes e capacidade produtiva'],['Construção modular','Sistemas pré-fabricados e soluções de projeto'],['Equipamentos comerciais e industriais','Equipamentos para operações comerciais, de serviços e produtivas'],['Soluções tecnológicas','Tecnologia aplicada a necessidades empresariais concretas'],['Sourcing personalizado','Pesquisa adaptada a requisitos específicos']] },
    process: { eyebrow: 'Como trabalhamos', title: 'Um processo estruturado, da necessidade à coordenação.', intro: 'Cada projeto começa pelos seus critérios, não por um catálogo.', items: [['Entender a necessidade','Definimos produto, equipamento ou tecnologia, quantidade, orçamento, requisitos, uso e objetivo.'],['Buscar fornecedores','Localizamos fabricantes e fornecedores potenciais no mercado chinês.'],['Avaliar e organizar','Reunimos informações empresariais e técnicas, preço, MOQ, prazo de entrega, condições de pagamento e requisitos técnicos.'],['Comparar alternativas','Apresentamos uma comparação estruturada das dimensões centrais para facilitar a avaliação do cliente.'],['Coordenar','Apoiamos a comunicação e a conexão posterior. A decisão comercial final cabe sempre ao cliente.']] },
    about: { eyebrow: 'Sobre nós', graphic: ['VÉRTICE','Perspectiva local','Acesso global','SINO'], title: 'Mais perto da China. Mais perto de uma boa decisão.', paragraphs: ['A Vértice Sino nasceu para ajudar empresas do Brasil e da América Latina a compreender e aproveitar a capacidade industrial chinesa com uma visão profissional, independente e orientada aos negócios.','Atuamos como consultores e facilitadores: oferecemos pesquisa, comparação e comunicação para que cada cliente mantenha o controle de suas decisões.'], link: 'Vamos conversar sobre seu projeto' },
    scope: { eyebrow: 'Nosso escopo', title: 'Clareza também é saber exatamente qual é o nosso papel.', intro: 'Acompanhamos a busca, avaliação e coordenação. A contratação e o pagamento são feitos diretamente entre o cliente e o fornecedor escolhido.', items: [['Análise e busca de fornecedores','Analisamos necessidades, buscamos fornecedores e organizamos e revisamos as informações recebidas.'],['Comparação e coordenação','Comparamos propostas e soluções e apoiamos a comunicação comercial com fornecedores na China.'],['Contratação direta','O cliente contrata e paga diretamente ao fornecedor final.'],['Pagamentos','Não recebemos valores de mercadorias nem pagamos fornecedores pelo cliente.'],['Importação','Não atuamos como importadora nem executamos a importação final no país do cliente.'],['Escopo profissional','Não vendemos produtos nem oferecemos tradução como serviço independente. A comunicação em chinês integra a consultoria e a coordenação do projeto.']] },
    faq: { eyebrow: 'Perguntas frequentes', title: 'Respostas claras antes de começar.', items: [['Como funciona o serviço?','Primeiro entendemos a necessidade. Depois buscamos fornecedores, organizamos e verificamos informações, comparamos alternativas e coordenamos o contato conforme a decisão do cliente.'],['Como é calculado o valor da consultoria?','Os honorários dependem da complexidade, do escopo da busca, do volume de pesquisa e dos serviços necessários. A proposta é apresentada antes do início.'],['A Vértice Sino importa os produtos?','Não. Prestamos consultoria de compras, busca e coordenação. O cliente cuida da importação conforme as regras do seu país ou com especialistas em comércio exterior e logística.'],['A quem o cliente paga?','O pagamento é feito diretamente ao fornecedor chinês selecionado. A Vértice Sino não recebe valores destinados à compra de mercadorias.'],['Como os fornecedores são selecionados?','Organizamos e comparamos o perfil do fornecedor, a adequação do produto e cinco dimensões centrais: preço, MOQ, prazo de entrega, condições de pagamento e requisitos técnicos. A análise reduz incertezas, mas não elimina todos os riscos.'],['Quanto tempo leva um projeto?','Depende da complexidade, dos requisitos técnicos, do tempo de resposta dos fornecedores, do número de alternativas e do escopo acordado.'],['Vocês buscam itens que não aparecem no site?','Sim. As áreas exibidas são referências. Podemos pesquisar outros produtos, equipamentos e tecnologias chinesas conforme uma necessidade empresarial específica.']] },
    contact: { eyebrow: 'Contato', title: 'Conte-nos o que sua empresa está buscando.', intro: 'Compartilhe os principais dados do projeto. Analisaremos a consulta para avaliar como podemos apoiar sua empresa.', whatsapp: ['Fale conosco pelo','WhatsApp'], fields: { name: ['Nome completo','Seu nome'], company: ['Empresa','Nome da empresa'], country: ['País','Brasil'], email: ['E-mail','nome@empresa.com'], whatsapp: ['WhatsApp / telefone (opcional)','Código do país e número'], product: ['Produto ou tecnologia procurada','O que você precisa encontrar?'], message: ['Descrição do projeto','Aplicação, requisitos técnicos e objetivos'], budget: ['Orçamento aproximado (opcional)','Faixa estimada'], quantity: ['Quantidade estimada (opcional)','Unidades ou volume'], deadline: ['Prazo esperado (opcional)','Data ou período estimado'] }, submit: 'Enviar consulta', privacy: 'Ao enviar, seu aplicativo de e-mail será aberto com a consulta preparada. Revise a mensagem e confirme o envio por lá.' },
    footer: { tagline: 'Conexões industriais com critério.', copyright: '© 2026 Vértice Sino' },
  },
  zh: {
    localeName: '简体中文', htmlLang: 'zh-CN',
    seo: { title: 'Vértice Sino｜中国供应商与现代制造技术咨询', description: '面向阿根廷及拉美企业的中国供应商寻源、评估、方案比较与产业对接咨询服务。' },
    nav: ['首页', '服务', '合作流程', '关于我们', '常见问题', '联系'], cta: '申请咨询', menuLabel: '打开菜单',
    hero: { eyebrow: '阿根廷 · 巴西 · 拉丁美洲', title: '连接您的企业与中国现代制造实力。', lead: '我们寻找、评估并对接中国供应商与技术方案，帮助企业在更充分的信息基础上做出采购决策。', process: '了解合作流程', note: ['让信息跨越边界，', '让决策推动业务前行。'], latam: '拉美', china: '中国', core: ['清晰洞察', '支持更好决策'], stats: [['市场','有针对性的调研'],['标准','可比的分析框架']] },
    trust: ['降低不确定性','提升方案可比性','促进高效沟通'],
    services: { eyebrow: '服务', title: '把企业的实际需求转化为中国市场中具体、可比较的选择。', intro: '我们将广泛而复杂的市场搜索，转化为具体、可比且与企业需求相关的选择。', items: [['中国供应商搜索与筛选','根据产品、设备、技术、预算、数量及项目目标，寻找潜在制造商。'],['供应商信息审查与交叉核对','整理供应商提供的信息，并对企业资料、产品信息、报价、MOQ（最低起订量）、交期及相关商务条件进行审查和交叉核对。'],['报价与方案比较','按照清晰的核心维度比较备选方案：价格、最低起订量、交期、付款条件和技术要求。'],['中文商务沟通与协调','作为寻源、评估及项目协调的一部分，直接与中国供应商进行必要的商务沟通。'],['现代制造与技术','根据实际需求探索智能制造、企业设备及新型生产技术。'],['自动化与机器人','寻找商业及工业自动化、服务机器人和智能设备解决方案。'],['模块化建筑','研究预制建筑及面向企业或具体项目的模块化方案。'],['供应商寻源咨询','针对网站未列出的产品、设备或技术开展研究并寻找合适制造方案。']] },
    capabilities: { eyebrow: '行业与解决方案', title: '我们可以协助寻找供应商和解决方案的主要领域。', intro: '我们不提供固定商品目录，而是根据企业的实际需求，在中国市场寻找合适的供应商、设备、技术和解决方案。', items: [['自动化与机器人','设备、集成与运营效率方案'],['先进制造','工艺、零部件与产能支持'],['模块化建筑','预制体系与项目型解决方案'],['商业与工业设备','适用于商业、服务及生产运营的设备'],['技术解决方案','面向企业具体需求的应用技术'],['定制化寻源','按照特定要求开展市场研究']] },
    process: { eyebrow: '合作流程', title: '从明确需求到项目协调，每一步都清晰有序。', intro: '每个项目都从客户的评估标准出发，而不是从产品目录出发。', items: [['理解真实需求','明确产品、设备或技术、数量、预算、技术要求、应用场景及项目目标。'],['寻找供应商','根据需求在中国市场寻找潜在供应商与制造商。'],['评估与整理','汇集企业资料和技术信息，并整理价格、MOQ、交期、付款条件及技术要求。'],['比较备选方案','围绕核心维度提供结构化的供应商和方案比较，帮助客户清晰判断。'],['沟通与协调','按照客户决定协助后续沟通与采购对接，最终商业决定始终由客户作出。']] },
    about: { eyebrow: '关于我们', graphic: ['VÉRTICE','本地视角','全球连接','SINO'], title: '更了解中国，更接近正确决策。', paragraphs: ['Vértice Sino 致力于帮助阿根廷及拉丁美洲企业，以专业、独立且面向商业成果的视角，理解并利用中国的现代工业能力。','我们是咨询顾问和对接伙伴，通过调研、比较与沟通支持客户，同时确保每位客户始终掌握自身决策的主动权。'], link: '与我们讨论您的项目' },
    scope: { eyebrow: '服务边界', title: '清晰的合作，也包括明确我们的角色。', intro: '我们陪伴客户完成搜索、评估与协调；最终合同和货款由客户与入选供应商直接处理。', items: [['需求分析与供应商搜索','分析客户需求，寻找供应商，并整理和审查所获得的信息。'],['比较与协调','比较报价和方案，并协助客户与中国供应商进行商务沟通和项目协调。'],['直接签约','客户直接与最终供应商签订合同并付款。'],['货款处理','我们不代收货款，也不代客户向供应商付款。'],['进口安排','我们不作为进口商，也不负责客户所在国家的最终进口操作。'],['专业范围','我们不是商品销售方，也不提供独立翻译服务；中文沟通是采购咨询与项目协调的一部分。']] },
    faq: { eyebrow: '常见问题', title: '开始合作前，先把重要问题说清楚。', items: [['服务如何开展？','我们首先理解客户需求，随后搜索供应商、整理并核实信息、比较备选方案，并根据客户决定协调后续沟通。'],['咨询服务如何收费？','费用取决于项目复杂度、搜索范围、研究工作量及所需服务内容。具体方案会在项目开始前说明。'],['Vértice Sino 负责进口吗？','不负责。我们提供采购咨询、供应商搜索和协调。客户按照所在国家规定自行安排进口，或委托专业进口及物流服务商。'],['客户向谁付款？','客户直接向最终选择的中国供应商付款。Vértice Sino 不代收商品货款。'],['如何筛选供应商？','我们综合整理供应商资料和产品匹配度，并重点比较五项核心维度：价格、最低起订量、交期、付款条件和技术要求。相关分析可降低不确定性，但不能承诺绝对无风险。'],['一个项目需要多长时间？','时间取决于产品复杂度、技术要求、供应商回复速度、需要比较的方案数量以及项目范围。'],['可以寻找网站未展示的产品或技术吗？','可以。网站展示的是主要方向，我们也可根据企业具体需求研究其他中国制造产品、设备和技术方案。']] },
    contact: { eyebrow: '联系我们', title: '请告诉我们您正在寻找什么。', intro: '请提供项目的主要信息。我们会评估您的需求，并确认可以如何提供支持。', whatsapp: ['通过以下方式联系我们','WhatsApp'], fields: { name: ['姓名','请输入您的姓名'], company: ['公司','公司名称'], country: ['国家或地区','阿根廷'], email: ['电子邮箱','name@company.com'], whatsapp: ['WhatsApp / 电话（选填）','国家代码和号码'], product: ['需要寻找的产品或技术','您希望寻找什么？'], message: ['项目说明','应用场景、技术要求与项目目标'], budget: ['大致预算（选填）','预计预算范围'], quantity: ['预计数量（选填）','单位或数量规模'], deadline: ['期望时间（选填）','预计日期或周期'] }, submit: '提交咨询', privacy: '提交后将打开您的邮件应用并生成咨询邮件。请检查邮件内容，然后在邮件应用中确认发送。' },
    footer: { tagline: '以专业判断连接产业机会。', copyright: '© 2026 Vértice Sino' },
  },
} as const;

export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }
